# Generated by Django 4.2 on 2023-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appimgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appimgs',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='appimgs',
            name='foto',
        ),
        migrations.AddField(
            model_name='appimgs',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/'),
        ),
    ]
