# Generated by Django 4.2 on 2023-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_titulo_appimgs_title_remove_appimgs_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appimgs',
            name='slug',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
